"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
const URL="https://tbaiovhgwbykaxpekyss.supabase.co";
const KEY="sb_publishable_tLRdeYrRgEDuGFX3fITyZw_4bouObbd";
const stages=["queue","working","checking","done"] as const;
const labels={queue:"Queue",working:"Working",checking:"Checking",done:"Done"} as Record<string,string>;
type Task={id:string;name:string;description:string|null;status:string;priority:string;reported_progress_percent:number|null;estimated_progress_percent:number|null;is_blocked:boolean};
type Session={access_token:string;user:{id:string;email?:string}};
function call(path:string,token?:string,options:RequestInit={}){return fetch(URL+path,{...options,headers:{apikey:KEY,Authorization:`Bearer ${token||KEY}`,"Content-Type":"application/json",Prefer:"return=representation",...(options.headers||{})}})}
export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[tasks,setTasks]=useState<Task[]>([]),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[details,setDetails]=useState(""),[priority,setPriority]=useState("medium"),[note,setNote]=useState("Sign in to load your real tasks."),[busy,setBusy]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem("tf-session");if(saved)setSession(JSON.parse(saved))},[]);
 const load=useCallback(async()=>{if(!session)return;const r=await call("/rest/v1/taskflow_tasks?select=*&archived_at=is.null&order=position.asc,created_at.desc",session.access_token);if(r.ok){setTasks(await r.json());setNote("Live data loaded from Sue.")}else if(r.status===401){localStorage.removeItem("tf-session");setSession(null);setNote("Please sign in again.")}else setNote("Sue could not load the tasks.")},[session]);
 useEffect(()=>{load();if(!session)return;const id=setInterval(load,15000);return()=>clearInterval(id)},[session,load]);
 async function auth(mode:"login"|"signup"){setBusy(true);const path=mode==="login"?"/auth/v1/token?grant_type=password":"/auth/v1/signup";const r=await call(path,undefined,{method:"POST",body:JSON.stringify({email,password})});const data=await r.json();if(r.ok&&data.access_token){setSession(data);localStorage.setItem("tf-session",JSON.stringify(data));setNote("Connected to Sue.")}else if(r.ok)setNote("Check your email, then sign in.");else setNote(data.msg||data.error_description||"Sign-in failed.");setBusy(false)}
 async function add(e:FormEvent){e.preventDefault();if(!session||!name.trim())return;setBusy(true);const r=await call("/rest/v1/taskflow_tasks",session.access_token,{method:"POST",body:JSON.stringify({owner_id:session.user.id,name:name.trim(),description:details.trim()||null,priority,status:"queue",reported_progress_percent:0})});if(r.ok){setName("");setDetails("");setNote("Task saved to Sue.");await load()}else setNote("Task could not be saved.");setBusy(false)}
 async function move(t:Task,d:-1|1){if(!session)return;const i=Math.max(0,stages.indexOf(t.status as typeof stages[number])),next=stages[Math.min(3,Math.max(0,i+d))],progress={queue:0,working:35,checking:80,done:100}[next];const r=await call(`/rest/v1/taskflow_tasks?id=eq.${t.id}`,session.access_token,{method:"PATCH",body:JSON.stringify({status:next,reported_progress_percent:progress,started_at:next==="working"?new Date().toISOString():undefined,completed_at:next==="done"?new Date().toISOString():null,updated_at:new Date().toISOString()})});if(r.ok){setNote(`Moved to ${labels[next]}.`);await load()}else setNote("Task could not be moved.")}
 const overall=useMemo(()=>tasks.length?Math.round(tasks.reduce((s,t)=>s+(t.reported_progress_percent??t.estimated_progress_percent??0),0)/tasks.length):0,[tasks]);
 if(!session)return <main className="login"><section><div className="brand"><b>TF</b><strong>TaskFlow <small>V3</small></strong></div><h1>Welcome back.</h1><p>Sign in to see tasks saved in Sue.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label><button disabled={busy} onClick={()=>auth("login")}>Sign in</button><button className="light" disabled={busy} onClick={()=>auth("signup")}>Create account</button><i>{note}</i></section></main>;
 return <main className="app"><header><div className="brand"><b>TF</b><strong>TaskFlow <small>V3 · Sue connected</small></strong></div><button className="logout" onClick={()=>{setSession(null);setTasks([]);localStorage.removeItem("tf-session")}}>Sign out</button></header><div className="hero"><div><em>TODAY&apos;S WORKSPACE</em><h1>Move work forward.</h1><p>{note}</p></div><div className="score">{overall}%<small>Overall progress</small></div></div><div className="stats"><span>All <b>{tasks.length}</b></span><span>Working <b>{tasks.filter(t=>t.status==="working").length}</b></span><span>Checking <b>{tasks.filter(t=>t.status==="checking").length}</b></span><span>Done <b>{tasks.filter(t=>t.status==="done").length}</b></span></div><form onSubmit={add}><input value={name} onChange={e=>setName(e.target.value)} placeholder="New task name" required/><input value={details} onChange={e=>setDetails(e.target.value)} placeholder="Optional details"/><select value={priority} onChange={e=>setPriority(e.target.value)}><option>low</option><option>medium</option><option>high</option></select><button disabled={busy}>Add task</button></form><div className="board">{stages.map(stage=><section className="column" key={stage}><h2><i className={stage}/>{labels[stage]}<b>{tasks.filter(t=>t.status===stage).length}</b></h2>{tasks.filter(t=>t.status===stage).map(t=>{const p=t.reported_progress_percent??t.estimated_progress_percent??0;return <article key={t.id}><small className={t.priority}>{t.priority}</small><h3>{t.name}</h3>{t.description&&<p>{t.description}</p>}<div className="bar"><span style={{width:`${p}%`}}/></div><small>{p}% {t.reported_progress_percent==null?"estimated":"reported"}</small><nav><button disabled={stage==="queue"} onClick={()=>move(t,-1)}>←</button><button disabled={stage==="done"} onClick={()=>move(t,1)}>Move →</button></nav></article>})}{!tasks.some(t=>t.status===stage)&&<div className="empty">No tasks here</div>}</section>)}</div></main>
}
